spring:
  datasource:
    username: root
    password: 258196
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrms?serverTimezone=UTC&characterEncoding=utf-8

  messages:
    basename: i18n.login,i18n.dashboard,i18n.staff,i18n.department,i18n.userprofile,i18n.error,i18n.add_new_user
    encoding: UTF-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
